- name: Declarative Onboarding (DO) playbook
  hosts: tag_Role_bigip
  connection: local
  vars_files: "{{ setupfile }}"

  tasks:
  
    - name: Set connection provider for BIG-IP tasks
      set_fact:
        provider:
          server: "{{ public_dns_name }}"
          server_port: 8443
          user: "{{ bigip.admin_user }}"
          password: "{{ bigip.admin_password }}"
          validate_certs: false

    - name: Wait for BIG-IP to be ready to take configuration
      bigip_wait:
        timeout: 600
        sleep: 10
        provider: "{{ provider }}"

    ######################
    # Precheck Licensing #
    ######################        
    - name: Verify DO licensing
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: GET
        atc_service: Device
        atc_delay: 20
        atc_retries: 60

    - name: Store result of DO license verification
      copy:
        content: |
          {{ (atc_GET_status.json is defined) | ternary(atc_GET_status.json | to_nice_json(indent=2), atc_GET_status.content) }}
        dest: "{{ outputfolder }}/do_precheck_result.json"

    - name: Check if a BIP-IP is licensed
      set_fact:
        perform_license: true
      when: 
        - atc_GET_status.content == "[]"
  
    - name: Check if a BIP-IP has revoked license
      set_fact:
        perform_license: true
      when:
        - atc_GET_status.json.declaration.Common.myLicense.revokeFrom is defined
        - atc_GET_status.json.declaration.Common.myLicense.revokeFrom == bigiq_license_pool
 
    ###############################
    # Do Licensing and Onboarding #
    ###############################        
    - name: Process jinja template and store result for artifact storage
      template:
        src: "templates/do/onboard.json.j2"
        dest: "{{ outputfolder }}/do_onboard.json"
        mode: 0644
      when: perform_license is defined and perform_license
      tags: onboard

    - name: Perform DO licensing and onboarding
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/do_onboard.json"
        atc_delay: 10
        atc_retries: 60
      when: perform_license is defined and perform_license
      tags: onboard

    - name: Store result of DO licensing and onboarding for artifact storage
      copy:
        content: |
          {{ (atc_DO_result.json is defined) | ternary(atc_DO_result.json | to_nice_json(indent=2), atc_DO_result.content) }}
        dest: "{{ outputfolder }}/do_onboard_result.json"
      when: perform_license is defined and perform_license
      tags: onboard

    ###############
    # Unlicensing #
    ###############
    - name: Process jinja template and store result for artifact storage
      template:
        src: "templates/do/unlicense.json.j2"
        dest: "{{ outputfolder }}/do_unlicense.json"
        mode: 0644
      tags: unlicense

    - name: Perform DO unlicensing
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_declaration_file: "{{ outputfolder }}/do_unlicense.json"
        atc_delay: 10
        atc_retries: 60
      tags: unlicense

    - name: Store result of DO unlicensing for artifact storage
      copy:
        content: |
          {{ (atc_DO_result.json is defined) | ternary(atc_DO_result.json | to_nice_json(indent=2), atc_DO_result.content) }}
        dest: "../output/do_unlicense_result.json"
      tags: unlicense

  ####################################
  # Manual verification on BIG-IP(s) #
  ####################################
  post_tasks:
    - name: Final result verification on BIG-IP 
      debug:
        msg: >
          Verify on BIG-IQ(s) if your desired results was achieved
            > Admin UI   : https://{{ public_dns_name }}:8443
            > REST URI   : https://{{ public_dns_name }}:8443/mgmt/shared/declarative-onboarding
            > DOCS URL   : https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest
            > SCHEMA REF : https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/schema-reference.html
            > GITHUB SRC : https://github.com/F5Networks/f5-declarative-onboarding

